name: courses_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  provider: ^6.0.5
  http: ^1.1.2
  flutter_pdfview: ^1.3.2
  in_app_review: ^2.0.6
  image_picker: ^1.0.1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  flutter_blurhash: ^0.8.2
  advance_pdf_viewer: ^2.0.1 
  flutter_inappwebview: ^6.1.5
  intl: ^0.18.1
  flutter_rating_bar: ^4.0.1
  device_info_plus: ^9.0.3
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.6.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  multi_select_flutter: ^4.1.3
  syncfusion_flutter_pdfviewer: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/test/

